### ISSUE TITLE
Uncaught TypeError: ml5.LSTMGenerator is not a function

### ISSUE THREAD

**Issue by sleepy-maker** [ml5js/training-lstm#8]
Seems that `README.md` needs small update for the latest version of ml5js.

I guess for the latest version, we need to use charRNN instead of LSTMGenerator.
Actually the following works to me.

```javescript
const lstm = ml5.charRNN('./dataset/', modelLoaded);
```

**Comment by yining1023** [comment]
Thank you for reporting it! It's fixed now.

**Comment by zenril** [comment]
It still says to use
ml5.LSTMGenerator
on the documentation

**Comment by sleepy-maker** [comment]
@zenril 
yeah, but actually the latest lib doesn't use LSTM anymore. The example has been updated.
https://github.com/ml5js/ml5-library/blob/master/src/CharRNN/index.js#L21
https://github.com/ml5js/ml5-examples/tree/master/p5js/LSTM/LSTM_Text

I guess the team is busy for something now.

**Comment by theunreal** [comment]
@yining1023 It's still errors at:

https://ml5js.org/docs/lstm-interactive-example
